# This is for non-cohort mode: 
# docker-compose run -e MUMBAI_SERVER=YOUR_END_POINT paciolinode
version: "3"
services:
  web:
    image: auditchainag/pacioli-node-helper
    container_name: web
    ports:
      - "3333:3333"
    networks:
      - audit_net
    environment:
      - TRANSACTION_SIGNER_PORT=3333
  paciolinode:
    image: auditchainag/paciolinode
    container_name: paciolinode
    stdin_open: true # docker run -i
    tty: true
    restart: always
    volumes:
      - '.:/secret'
      - '.:/workdir'
    command: /bin/bash
    networks:
      - audit_net
    depends_on:
      - web
    environment:
      - TRANSACTION_SIGNER_PORT=3333
      - TRANSACTION_SIGNER_URL=http://web
      - PACIOLI_ENV=PacioliNode.env
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
networks:
  audit_net:
    driver: bridge
