# For cohort mode: docker compose -f docker-compose-cohort.yml run paciolinode
version: "3"
services:
  web:
    image: auditchainag/pacioli-node-helper
    container_name: web
    ports:
      - "3333:3333"
    networks:
      - audit_net
    environment:
      - TRANSACTION_SIGNER_PORT=3333
      - MODE=cohort
  paciolinode:
    image: auditchainag/paciolinode
    container_name: paciolinodecohort
    stdin_open: true # docker run -i
    tty: true
    restart: always
    volumes:
      - '.:/secret'
      - '.:/workdir'
    entrypoint: ["node","scripts/pacioliAgentCohort.js"]
    working_dir: /software/PacioliAgent
    networks:
      - audit_net
    depends_on:
      - web
    environment:
      - MODE=cohort
      - TRANSACTION_SIGNER_PORT=3333
      - TRANSACTION_SIGNER_URL=http://web
      - PACIOLI_ENV=PacioliNode.env
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
networks:
  audit_net:
    driver: bridge
